name: release

on:
  push:
    branches:
      - main

env:
  DAGGER_NO_NAG: "1"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Call Dagger Function to release
        uses: dagger/dagger-for-github@v8.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          call: semantic-release run --repo-token-env GITHUB_TOKEN --repo-token env:GITHUB_TOKEN --ci=true --dry-run=false

  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ needs.release.outputs.tag }}
          fetch-depth: 0

      - name: Call Dagger Function to build and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: dagger/dagger-for-github@v8.4.1
        with:
          call: goreleaser release --token-env GITHUB_TOKEN --token env:GITHUB_TOKEN
